- .gitignore
- README.md
- packages/syberos-cli/bin/syberos
- packages/syberos-cli/bin/syberos-doctor
- packages/syberos-cli/src/build/build.ts
- packages/syberos-cli/src/doctor/index.ts
- packages/syberos-cli/src/doctor/pdkSdkValidator.ts
- packages/syberos-cli/src/syberos/helper.ts
增加README；
增加syberos doctor命令，简单实现检查pdk和sdk；
增加syberos simulator命令启动模拟器；
忽略js子目录中的dist目录
> 增加syberos可用指令

- website/sidebars.json
> Bugfix: 调整目录

- packages/syberos-template/com/syberos/core/js/config.js
- packages/syberos-template/com/syberos/core/js/core/core.js
- packages/syberos-template/com/syberos/core/js/core/plugin.js
- packages/syberos-template/com/syberos/core/js/modal/alert.js
- packages/syberos-template/com/syberos/core/js/readme.md
- packages/syberos-template/com/syberos/core/js/util/polyfill.js
- packages/syberos-template/com/syberos/core/js/webview/webview.js
feat(template): 增加参数拓展
feat(teplate): 优化事件函数,增加多个参数传递
feat(template): 增加回调示例
docs: 增加插件使用方式
> feat(template): 增加webview全局变量

- docs/apis/modal/alert.md
- docs/apis/modal/confirm.md
- docs/apis/modal/prompt.md
- docs/apis/modal/toast.md
文档修改(Docs)
提交到 master 分支
syberos-docs
> docs: 修改modal模块, 新增success, error回调方法

- packages/syberos-template/com/syberos/core/js/config.js
- packages/syberos-template/com/syberos/core/js/core/core.js
- packages/syberos-template/com/syberos/core/js/webview/webview.js
- packages/syberos-template/com/syberos/core/qml/swebview.qml
perf(template): 优化插件加载方式
feat(template): 增加webview返回键监听
> feat(template): 增加返回按键key值

- packages/syberos-template/com/syberos/core/qml/SBarcode.qml
> fix(template): 调整扫码提示字体大小

- .gitignore
> refactor: 增加website编译忽略

- docs/apis/modal/gtoast.md
- docs/apis/modal/toast.md
- docs/apis/webview/webview.md
- packages/syberos-template/com/syberos/api/js/webview/webview.js
- website/i18n/en.json
- website/sidebars.json
.com/syberos-team/syberos-hybrid/blob/master/CONTRIBUTING.md
-->
> docs: 文档描述变更

- packages/syberos-cli/package.json
- packages/syberos-dev-server/package.json
- packages/syberos-jsbridge/package.json
- packages/syberos-template/package.json
> refactor: lerna 发布执行

- packages/syberos-cli/src/build/build.ts
- packages/syberos-cli/templates/default/platforms/syberos/tests/tests.pro
- packages/syberos-template/jscript/publish.js
fix(template): 拷贝项目时增加tests子目录
> fix(template): 拷贝项目时增加tests子目录

- packages/syberos-template/app/app.pro
- packages/syberos-template/app/src/App_Workspace.cpp
- packages/syberos-template/app/src/App_Workspace.h
- packages/syberos-template/app/src/main.cpp
> fix(template): 重命名workspace

- packages/syberos-template/app/www/pages/network.html
> fix(template): 修改网络示例样式

- packages/syberos-cli/src/build/build.ts
> fix(cli): 修改build时查找cdb设备的问题

- packages/syberos-template/app/www/index.html
- packages/syberos-template/app/www/pages/camera.html
- packages/syberos-template/app/www/pages/clipboard.html
- packages/syberos-template/com/syberos/api/qml/SCamera.qml
> feat(clipboard): 调整剪切板显示，修复相机状态栏显示

- packages/syberos-cli/templates/default/platforms/syberos/app/www/index.html
- packages/syberos-cli/templates/default/platforms/syberos/app/www/pages/camera.html
- packages/syberos-cli/templates/default/platforms/syberos/app/www/pages/clipboard.html
- packages/syberos-cli/templates/default/platforms/syberos/com/syberos/api/qml/SCamera.qml
- packages/syberos-cli/templates/default/platforms/syberos/com/syberos/api/qml/SToast.qml
> feat(clipboard): 编译剪切板修改的代码

- packages/syberos-cli/src/build.ts
- packages/syberos-cli/src/build/build.ts
- packages/syberos-cli/src/build/index.ts
- packages/syberos-cli/src/syberos/helper.ts
- packages/syberos-cli/src/util/constants.ts
- packages/syberos-cli/templates/default/pkg
> CLI新增build打包命令

- docs/apis/clipboard/getClipboardData.md
- docs/apis/clipboard/setClipboardData.md
- docs/apis/modal/alert.md
- docs/apis/modal/confirm.md
- docs/apis/modal/gtoast.md
- docs/apis/modal/prompt.md
- docs/apis/modal/toast.md
- docs/apis/multimedia/camera/capturePhoto.md
- docs/apis/request/request.md
- docs/apis/storage/getAllKeys.md
- docs/apis/storage/getItem.md
- docs/apis/storage/removeItem.md
- docs/apis/storage/setItem.md
- docs/apis/system/aboutPhone.md
- docs/apis/telephony/dial.md
> docs: 隐藏Pormise写法

- docs/apis/about/desc.md
- docs/apis/storage/removeItem.md
- docs/apis/storage/setItem.md
- docs/apis/telephony/dial.md
> docs: 修改文档， 注释掉无用的代码

- docs/started-syberos.md
- website/core/Footer.js
>  docs(docs): 修改文档中下载路径

- docs/apis/request/request.md
- packages/syberos-template/com/syberos/api/src/network.cpp
> docs: 修改下载模块文档

- docs/started-syberos.md
> docs(docs): 添加网盘下载地址

- packages/syberos-cli/bin/syberos-build
- packages/syberos-cli/src/build/build.ts
- packages/syberos-cli/src/create/project.ts
> fix(cli): 修改创建示例项目提示, 修改build命令帮助信息和打印信息

- packages/syberos-cli/package.json
> chore(release): publish 1.0.0

- README.md
> docs: 修改主项目README

- website/i18n/en.json
- website/sidebars.json
> docs: 更新URL文档

- .gitignore
> chore: 修改忽略

- packages/template/com/syberos/api/src/url.cpp
> feat(template): 修改唤起应用bug

- docs/README.md
- website/versioned_docs/version-1.1.0/README.md
> docs(readme): 修改全局命令为syberh

- packages/cli/dist/create/project.js
- packages/cli/src/create/project.ts
- packages/cli/src/syberos/configfile.ts
- packages/cli/templates/default/index.js
feat(cli): init命令创建项目时，手动选择target
> feat(cli): init命令创建项目时，手动选择target

- packages/cli/dist/doctor/pdkSdkValidator.js
- packages/cli/src/doctor/pdkSdkValidator.ts
- packages/cli/src/doctor/sdkValidator.ts
- packages/cli/templates/default/index.js
> chore: 增加expect检查

- packages/template/com/syberos/api/js/modal/toast.js
- packages/template/com/syberos/api/qml/SToast.qml
> feat(template): 修改toast bug

- packages/cli/bin/syberh-build
- packages/cli/bin/syberh-doctor
- packages/cli/dist/build.js
- packages/cli/dist/doctor/index.js
- packages/cli/src/build.ts
- packages/cli/src/build/index.ts
- packages/cli/src/doctor/index.ts
- packages/cli/src/util/types.ts
- packages/cli/templates/default/www/pages/gtoast.html
- packages/cli/templates/default/www/pages/toast.html
- packages/cli/templates/default/www/pages/url.html
feat(cli): build指令默认会使用doctor检查环境，增加--nodoctor参数构建时关闭环境检查
> feat(cli): build指令默认会使用doctor检查环境，增加--nodoctor参数构建时关闭环境检查

- docs/apis/storage/removeAll.md
- website/i18n/en.json
- website/sidebars.json
> docs(docs): 数据存储增加删除全部

- docs/started-ide.md
- packages/cli/dist/build.js
- packages/cli/dist/build/build.js
- packages/cli/dist/doctor/index.js
- packages/cli/src/build.ts
- packages/cli/src/build/build.ts
- packages/cli/src/doctor/index.ts
- website/versioned_docs/version-1.1.0/started-ide.md
fix(cli): build指令编译时，DEV_LOG添加至扩展参数中
> fix(cli): build指令编译时，DEV_LOG添加至扩展参数中

- packages/template/com/syberos/api/js/util/tool.js
> fix(template): 修复parse异常

- .github/PULL_REQUEST_TEMPLATE.md
> fix: 修复拼写错误

- packages/template/app/www/pages/camera.html
- packages/template/com/syberos/api/js/camera/capture.js
> feat(camera): 修复相机返回和二次点击bug

- packages/template/com/syberos/api/src/util/log.cpp
- packages/template/com/syberos/api/src/util/log.h
> feat(cli): 日志类增加自定义颜色输出

- packages/template/com/syberos/api/src/framework/common/errorinfo.cpp
> fix(template): 修改格式化错误消息的问题

- packages/template/com/syberos/api/src/cellular.cpp
- packages/template/com/syberos/api/src/framework/common/extendedconfig.cpp
- packages/template/com/syberos/api/src/framework/common/extendedconfig.h
- packages/template/com/syberos/api/src/framework/common/networkstatus.cpp
- packages/template/com/syberos/api/src/networkInfo.cpp
- packages/template/com/syberos/api/src/util/log.cpp
> fix(template): 析构时删除单例对象

- packages/template/com/syberos/api/js/filepicker/filepicker.js
- packages/template/com/syberos/api/qml/SFilesPicker.qml
- packages/template/com/syberos/api/qml/SFilesPickerView.qml
- packages/template/com/syberos/api/qml/SWebview.qml
> 重构webview中的filepicker功能组件

- packages/template/com/syberos/api/src/upload.cpp
> fix(template): 修改编译警告

- packages/template/app/www/index.html
- packages/template/app/www/pages/webview-ext.html
- packages/template/com/syberos/api/qml/SDelegateComponent.qml
- packages/template/com/syberos/api/qml/SWebview.qml
> feat: 增加文件多选处理

- packages/syberos/README.md
> chore(syberos): 增加README

- docs/started-spm.md
> docs: 修改spm文档示例

- packages/cli/src/doctor/spmValidator.ts
> fix: 修复doctor在spm检查时一直报警告的问题

- lerna.json
> fix: 修改lerna管理的包名

- docs/specials.md
> docs(specials): 修改下载项目用最新的tag版本

- docs/specials.md
> docs(specials): 修改注意文字

- website/i18n/en.json
- website/sidebars.json
- website/siteConfig.js
> docs: 文档中的常见问题与指南、api平级

- docs/app-webPath.md
- docs/cli-readme.md
- packages/cli/bin/syberh-doctor
- packages/cli/src/build.ts
- packages/cli/src/create/project.ts
- packages/cli/src/doctor/index.ts
- packages/cli/src/doctor/targetSdkValidator.ts
- packages/cli/templates/default/index.js
- packages/cli/templates/default/project
- website/i18n/en.json
- website/sidebars.json
> init创建项目, project.config.json文件新增webPath参数, doctor新增--global子命令

- docs/apis/database/execute.md
> docs: 数据库操作-操作文档修改

- website/siteConfig.js
> docs: 修改文档

- packages/build.sh
> chore: 增加本地编译打包脚本

- packages/syberos/app/www/pages/download.html
> fix: 修复下载、上传bug；prompt点击无反应；toast返回码有误

- packages/syberos/app/www/pages/openDocument.html
> fix(syberos): 修改示例项目中的sopid

- packages/cli/src/build/build.ts
- packages/cli/src/build/index.ts
> fix: 将启动热更新服务调整至打包完成后执行

- packages/cli/scripts/devServer.js
> fix(cli): 修改热更新参数名错误导致的问题

- packages/cli/templates/default/platforms/syberos/vendor/syberh-framework/js/util/log.js
- packages/cli/templates/default/platforms/syberos/vendor/syberh-framework/js/webview/webview.js
- packages/cli/templates/default/platforms/syberos/vendor/syberh-framework/src/helper.cpp
- packages/cli/templates/default/www/index.html
- packages/cli/templates/default/www/pages/router.html
- packages/syberos/app/www/index.html
- packages/syberos/app/www/pages/router.html
> fix: 修复onShow订阅事件触发不正确的问题

- docs/specials.md
- packages/cli/src/doctor/syberhValidator.ts
- packages/dev-server/dist/server/HttpServer.js
- packages/dev-server/src/server/HttpServer.ts
> 修复热更新下载路径错误的问题，修复doctor命令获取不到本地版本的问题，新增升级后项目不能运行的常见问题

- website/siteConfig.js
> feat: 增加站内搜索

- packages/cli/src/build/connect.ts
> fix(cli): 修改部分cdb模式手机无法检测到设备的问题

- docs/global-event.md
- packages/syberos/app/www/index.html
> 新增监听设备物理按键

- docs/app-config.md
- packages/cli/scripts/devServer.js
- packages/cli/src/build/index.ts
> feat(cli): 热更新修改为监听工程指定的webPath目录, 修改app配置文档热更新目录限制为根目录下

- website/siteConfig.js
- website/static/js/buttons.js
> docs: 修改button.js从github访问改成本地文件, 去掉返回到顶部按钮(国外网站访问较慢)

- docs/vue-use-syberh.md
- website/i18n/en.json
- website/sidebars.json
> docs: 新增vue项目使用syberh

- packages/syberos/app/qml/framework/SWebview.qml
- packages/syberos/app/qml/framework/SWebview59.qml
- packages/syberos/app/qml/framework/js/webview/webview.js
> fix: 将按键事件统一为keyEvent接口，增加按键按下事件

- packages/cli/scripts/sb2-build-plugins.sh
- packages/cli/scripts/scp-sop.sh
- packages/cli/scripts/ssh-install-sop.sh
- packages/cli/scripts/ssh-start-app.sh
- packages/cli/src/build/build.ts
- packages/cli/src/build/compile.ts
- packages/cli/src/build/connect.ts
- packages/cli/src/build/index.ts
- packages/cli/src/build/sop.ts
- packages/cli/src/build/types.ts
- packages/cli/src/syberos/helper.ts
- packages/cli/src/syberos/localConfig.ts
- packages/syberos/app/qml/framework/SWebview4.qml
- packages/syberos/nativesdk/src/framework/common/projectconfig.h
> refactor: 优化非5.0系统插件编译

- docs/apis/system/aboutPhone.md
- docs/apis/system/captureScreen.md
- docs/apis/system/date.md
- packages/jsbridge/src/api/native/system.js
- packages/syberos/app/www/pages/system.html
- website/i18n/en.json
- website/sidebars.json
Signed-off-by: Li Hejia <lihejia@syberos.com>
> feat: 增加截屏api

- docs/apis/image/saveImageToPhotosAlbum.md
- docs/apis/multimedia/record/start.md
- docs/apis/system/battery.md
- packages/syberos/app/www/pages/record.html
> 增加录音接口可配置参数，修改录音，电量，保存图片文档

- docs/cli-readme.md
> docs: 修改cli工具新增命令文档

- packages/syberos/nativesdk/src/framework/devtools/devdownload.cpp
- packages/syberos/nativesdk/src/framework/devtools/devdownload.h
- packages/syberos/nativesdk/src/framework/devtools/devtools.cpp
- packages/syberos/nativesdk/src/framework/devtools/devtools.h
- packages/syberos/nativesdk/src/framework/devtools/devtools_os5.cpp
- packages/syberos/nativesdk/src/framework/devtools/socketclient.cpp
- packages/syberos/nativesdk/src/framework/devtools/socketclient.h
- packages/syberos/nativesdk/src/framework/nativesdkfactory.cpp
- packages/syberos/nativesdk/src/framework/nativesdkfactory.h
- packages/syberos/nativesdk/src/framework/nativesdkhandlerbase.cpp
- packages/syberos/nativesdk/src/framework/nativesdkhandlerbase.h
- packages/syberos/nativesdk/src/framework/nativesdkmanager.cpp
- packages/syberos/nativesdk/src/framework/nativesdkmanager.h
- packages/syberos/nativesdk/src/framework/pluginadapter.cpp
- packages/syberos/nativesdk/src/framework/pluginadapter.h
- packages/syberos/nativesdk/src/helper.cpp
- packages/syberos/nativesdk/src/helper.h
- packages/syberos/nativesdk/src/qmlmanager.h
- packages/syberos/nativesdk/src/util/fileutil.cpp
- packages/syberos/nativesdk/src/util/fileutil.h
- packages/syberos/pluginmanager/src/iplugin/iplugin.cpp
- packages/syberos/pluginmanager/src/iplugin/iplugin.h
> chore: 修改参数传递地址

- packages/cli/src/syberos/helper.ts
> fix: 修复编译项目时无法通过检查密码的问题

- docs/apis/packages/openDocument.md
- docs/apis/packages/openUrl.md
> docs: 修改packages文档

- packages/cli/src/build/build.ts
- packages/syberos/app/www/index.html
- packages/syberos/app/www/pages/webview-ext.html
- packages/syberos/nativesdk/src/framework/common/projectconfig.h
> 修复应用退出及toast显示问题

- packages/cli/bin/syberh-build
- packages/cli/src/build/build.ts
- packages/cli/src/build/compile.ts
- packages/cli/src/build/types.ts
> feat: build编译时可选择插件或编译任何插件

- packages/syberos/app/www/pages/webview-ext.html
> chore: goBack示例

- lerna.json
- packages/cli/package.json
- packages/jsbridge/package.json
- packages/syberos/VERSION
- packages/syberos/package.json
> chore: 发布2.2.2-alpha.3

- docs/apis/multimedia/record/start.md
- docs/cli-readme.md
- packages/cli/bin/syberh-doctor
- packages/cli/bin/syberh-update
- packages/syberos/app/qml/cwebview/CWebView.qml
> 出现证书错误时，弹出确认对话框

- lerna.json
- packages/cli/package.json
- packages/jsbridge/package.json
- packages/syberos/VERSION
- packages/syberos/package.json
> chore: 发布2.2.2-beta.1

- packages/cli/scripts/sb2-build-plugins.sh
- packages/syberos/app/www/index.html
- packages/syberos/app/www/pages/iframe/iframe.html
- packages/syberos/app/www/pages/iframe/index.html
> fix: 修复因显示不全kchroot返回信息时导致不能继续

- lerna.json
- packages/cli/package.json
- packages/jsbridge/package.json
- packages/syberos/VERSION
- packages/syberos/package.json
> chore: 发布2.2.2-beta.2

- packages/syberos/app/qml/js/util/log.js
- packages/syberos/app/qml/js/webview/webview.js
> fix: os5.0中qtwebengine忽略按键事件后，直接返回桌面的问题

- packages/syberos/app/qml/js/webview/webview.js
> fix: 只在在释放返回按键时处理，防止多次触发返回

- lerna.json
- packages/cli/package.json
- packages/jsbridge/package.json
- packages/syberos/VERSION
- packages/syberos/package.json
> chore: 发布2.2.2-beta.4

- docs/apis/brightness/setAmbientLightSensorEnabled.md
- docs/apis/brightness/setBlankTimeout.md
- docs/apis/brightness/setBrightness.md
- docs/apis/brightness/setDimTimeout.md
- packages/syberos/app/www/pages/network.html
- packages/syberos/app/www/pages/setBrightness.html
- packages/syberos/app/www/pages/webengine/index.html
- packages/syberos/nativesdk/nativesdk.pro
- packages/syberos/nativesdk/src/framework/common/networkstatus.cpp
- packages/syberos/nativesdk/src/framework/common/networkstatus.h
- packages/syberos/nativesdk/src/util/util.cpp
- packages/syberos/nativesdk/src/util/util.h
- packages/syberos/nativesdk/src/util/validator.cpp
>  fix: 修改息屏时长接口

- docs/apis/request/request.md
- packages/jsbridge/src/api/native/network.js
- packages/syberos/app/src/main.cpp
- packages/syberos/app/www/pages/network.html
- packages/syberos/nativesdk/src/util/util.h
- packages/syberos/pluginmanager/src/iplugin/iplugin.cpp
- packages/syberos/pluginmanager/src/iplugin/iplugin.h
- website/i18n/en.json
> feat: 修改插件接口
